### ISSUE TITLE
speech medium v2

### ISSUE THREAD

**Issue by theodorblackbird** [jishengpeng/WavTokenizer#37]
Hi,
Thank you for sharing this work.
I've seen a recently uploaded "v2" version for the medium speech model.
It seems not backward compatible, how does it differ from the first version ?

**Comment by jishengpeng** [comment]
> Hi, Thank you for sharing this work. I've seen a recently uploaded "v2" version for the medium speech model. It seems not backward compatible, how does it differ from the first version ?

v1 and v2 differ only in the number of training steps, with v2 being trained for a longer duration.
