### ISSUE TITLE
Abnormal audio exists in generated audio

### ISSUE THREAD

**Issue by xinkez** [jishengpeng/WavTokenizer#4]
Hi，

when I use your pre-trained model to encode and decode audio, I found that there is abnormal audio in the beginning and end of the reconstructed wav. Thanks.

original:
![image](https://github.com/user-attachments/assets/28601d45-b82a-4756-ba4c-e784eaaab3b7)

reconstruncted:
![image](https://github.com/user-attachments/assets/06d912ef-7810-4589-98b4-9ade1b707ef1)

**Comment by jishengpeng** [comment]
> Hi，
> 
> when I use your pre-trained model to encode and decode audio, I found that there is abnormal audio in the beginning and end of the reconstructed wav. Thanks.
> 
> original: ![image](https://private-user-images.githubusercontent.com/13937138/363568443-28601d45-b82a-4756-ba4c-e784eaaab3b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTg1NTEsIm5iZiI6MTcyNTI1ODI1MSwicGF0aCI6Ii8xMzkzNzEzOC8zNjM1Njg0NDMtMjg2MDFkNDUtYjgyYS00NzU2LWJhNGMtZTc4NGVhYWFiM2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA2MjQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2YTMxZjBkMDNhMjQwZGUwZjFmNWU3NjY4ZjM5ZTlmMzBiMDRhNjljMDljNDY0NTU1MjJkMzdhMTJmZDRmZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VvhQBQ7Wy-pAEesxRxtE646cAAYXnIyl42jEe00cqsI)
> 
> reconstruncted: ![image](https://private-user-images.githubusercontent.com/13937138/363568365-06d912ef-7810-4589-98b4-9ade1b707ef1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTg1NTEsIm5iZiI6MTcyNTI1ODI1MSwicGF0aCI6Ii8xMzkzNzEzOC8zNjM1NjgzNjUtMDZkOTEyZWYtNzgxMC00NTg5LTk4YjQtOWFkZTFiNzA3ZWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA2MjQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZDkyOTFmZWE1YjI3MjE4OTQwYjU1OWJhOWYzMjA5ZTY5YmRlODJhNmU4ZmFkZmIwNTVmZWIyZDI2NGI3NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.USIMszwpLyYin1yLQffcs3qEri-b33KqDozbMc3PyFM)

Thank you for using WavTokenizer.

The WavTokenizer-small model has been trained exclusively in the speech domain and lacks training in the broader audio domain. Due to its training on only 500 hours of data, its generalization capabilities are significantly limited, which may result in noise when applied to out-of-domain speech data. However, we have internally tested the WavTokenizer-medium version, which demonstrates greatly improved generalization.

Additionally, you may consider evaluating the WavTokenizer-small version on the LibriTTS test-clean dataset, where it is expected to perform without the aforementioned noise issues.

**Comment by xinkez** [comment]
> > Hi，
> > when I use your pre-trained model to encode and decode audio, I found that there is abnormal audio in the beginning and end of the reconstructed wav. Thanks.
> > original: ![image](https://private-user-images.githubusercontent.com/13937138/363568443-28601d45-b82a-4756-ba4c-e784eaaab3b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTg1NTEsIm5iZiI6MTcyNTI1ODI1MSwicGF0aCI6Ii8xMzkzNzEzOC8zNjM1Njg0NDMtMjg2MDFkNDUtYjgyYS00NzU2LWJhNGMtZTc4NGVhYWFiM2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA2MjQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2YTMxZjBkMDNhMjQwZGUwZjFmNWU3NjY4ZjM5ZTlmMzBiMDRhNjljMDljNDY0NTU1MjJkMzdhMTJmZDRmZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VvhQBQ7Wy-pAEesxRxtE646cAAYXnIyl42jEe00cqsI)
> > reconstruncted: ![image](https://private-user-images.githubusercontent.com/13937138/363568365-06d912ef-7810-4589-98b4-9ade1b707ef1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTg1NTEsIm5iZiI6MTcyNTI1ODI1MSwicGF0aCI6Ii8xMzkzNzEzOC8zNjM1NjgzNjUtMDZkOTEyZWYtNzgxMC00NTg5LTk4YjQtOWFkZTFiNzA3ZWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA2MjQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZDkyOTFmZWE1YjI3MjE4OTQwYjU1OWJhOWYzMjA5ZTY5YmRlODJhNmU4ZmFkZmIwNTVmZWIyZDI2NGI3NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.USIMszwpLyYin1yLQffcs3qEri-b33KqDozbMc3PyFM)
> 
> Thank you for using WavTokenizer.
> 
> The WavTokenizer-small model has been trained exclusively in the speech domain and lacks training in the broader audio domain. Due to its training on only 500 hours of data, its generalization capabilities are significantly limited, which may result in noise when applied to out-of-domain speech data. However, we have internally tested the WavTokenizer-medium version, which demonstrates greatly improved generalization.
> 
> Additionally, you may consider evaluating the WavTokenizer-small version on the LibriTTS test-clean dataset, where it is expected to perform without the aforementioned noise issues.

Thanks for your reply.

**Comment by cahya-wirawan** [comment]
I finetuned the small model with only one speaker, the generator/total_loss is around 50. But when I try to encode and decode an audio from the same speaker,  I have similar issue with the decoded audio. the end of audio has an klick sound that doesn't exist in the original audio.
