### ISSUE TITLE
How many training steps to train wavtokenizer?

### ISSUE THREAD

**Issue by sphmel** [jishengpeng/WavTokenizer#43]
@jishengpeng 
https://huggingface.co/novateur/WavTokenizer/blob/main/wavtokenizer_smalldata_frame40_3s_nq1_code4096_dim512_kmeans200_attn.yaml

in config above num_steps are 20000000, which is 10M steps for generator and discriminator, but comment says 1M steps per module, and paper says model is trained 500K steps per module

what is true?

**Comment by jishengpeng** [comment]
> @jishengpeng https://huggingface.co/novateur/WavTokenizer/blob/main/wavtokenizer_smalldata_frame40_3s_nq1_code4096_dim512_kmeans200_attn.yaml
> 
> in config above num_steps are 20000000, which is 10M steps for generator and discriminator, but comment says 1M steps per module, and paper says model is trained 500K steps per module
> 
> what is true?

1M
