### ISSUE TITLE
some questions about model

### ISSUE THREAD

**Issue by VJJJJJJ1** [jishengpeng/WavTokenizer#49]
hi, thank you for your great work, I have some questions:
1. As you mentioned in the paper: ```adding the attention module before the ConvNext module appears to be the optimal solution.```，but I found that in ```decoder/models.py```, the AttnBlock is contained in pos_net which is after convnext. They seem to be in the opposite order as in the paper.
2. I want to do streaming inference with wavtokenizer, I have replaced all the convolution layers in SEANetEncoder, SEANetDecoder, ConvNeXtBlock and pos_net(ResnetBlock+AttnBlock) with causal convolution layers(class SConv1d with causal=T). Unfortunately, the genetrator loss keeps increasing(see in the pic). Is there any wrong in the modified model?  

thank you for your reply!
![image](https://github.com/user-attachments/assets/a24851f8-3d8a-4691-a66d-898445574093)

**Comment by jishengpeng** [comment]
> hi, thank you for your great work, I have some questions:
> 
> 1. As you mentioned in the paper: `adding the attention module before the ConvNext module appears to be the optimal solution.`，but I found that in `decoder/models.py`, the AttnBlock is contained in pos_net which is after convnext. They seem to be in the opposite order as in the paper.
> 2. I want to do streaming inference with wavtokenizer, I have replaced all the convolution layers in SEANetEncoder, SEANetDecoder, ConvNeXtBlock and pos_net(ResnetBlock+AttnBlock) with causal convolution layers(class SConv1d with causal=T). Unfortunately, the genetrator loss keeps increasing(see in the pic). Is there any wrong in the modified model?
> 
> thank you for your reply! ![image](https://private-user-images.githubusercontent.com/77922137/384802233-a24851f8-3d8a-4691-a66d-898445574093.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMTgwMTgsIm5iZiI6MTczMTMxNzcxOCwicGF0aCI6Ii83NzkyMjEzNy8zODQ4MDIyMzMtYTI0ODUxZjgtM2Q4YS00NjkxLWE2NmQtODk4NDQ1NTc0MDkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA5MzUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZGJiZjk2MGI2NGYwZDczZTVjNzkwNjM5ZjkzY2M4ZjUzZTViNDZmYjRjN2ZlMTk4ZTE5Njg0Y2RiZjc1YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xKMBoCYPPPN1paS9I_NRZo6JxTSsql8A68xeOkSedR4)

1. The code is consistent with the paper, with the attention module placed before the ConvNeXt blocks. [https://github.com/jishengpeng/WavTokenizer/blob/02c66cbb4b05b3ee225419f00f3914eb1854b7d5/decoder/models.py#L225](Link)
2. We have also experimented with WavTokenizer-Streaming and found the performance to be satisfactory. The issue you are encountering appears to be a bug or some other underlying cause. During modification, only the parameters of the encoder need to be adjusted, while for the decoder, detailed changes to the attention and convolution modules are required.

**Comment by VJJJJJJ1** [comment]
> 1. The code is consistent with the paper, with the attention module placed before the ConvNeXt blocks. [Link](https://github.com/jishengpeng/WavTokenizer/blob/02c66cbb4b05b3ee225419f00f3914eb1854b7d5/decoder/models.py#L225)
> 2. We have also experimented with WavTokenizer-Streaming and found the performance to be satisfactory. The issue you are encountering appears to be a bug or some other underlying cause. During modification, only the parameters of the encoder need to be adjusted, while for the decoder, detailed changes to the attention and convolution modules are required.

thank you for your reply. I will try it. BTW, should I add mask in AttnBlock?

**Comment by VJJJJJJ1** [comment]
> 1. The code is consistent with the paper, with the attention module placed before the ConvNeXt blocks. [Link](https://github.com/jishengpeng/WavTokenizer/blob/02c66cbb4b05b3ee225419f00f3914eb1854b7d5/decoder/models.py#L225)
> 2. We have also experimented with WavTokenizer-Streaming and found the performance to be satisfactory. The issue you are encountering appears to be a bug or some other underlying cause. During modification, only the parameters of the encoder need to be adjusted, while for the decoder, detailed changes to the attention and convolution modules are required.

In fact, the loss curve was the same when I didn't change the code (on both libritts and ljspeech), and I didn't understand why this was the case, I just changed the following configuration:
```
data:
  class_path: decoder.dataset.VocosDataModule
  init_args:
    train_params:
      filelist_path:./data/LJSPEECH/train.txt
      sampling_rate: 24000
      num_samples: 24000
      batch_size: 16  # 20
      num_workers: 8

    val_params:
      filelist_path: ./data/LJSPEECH/val.txt
      sampling_rate: 24000
      num_samples: 24000
      batch_size: 5   # 10
      num_workers: 8
```

**Comment by tanmaylaud** [comment]
Hi, can you share the code changes for the streaming setup ? It will be great if you can share the model weights as well
